name: Serverless Function CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Info List
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Get Only needed files
        uses: actions/upload-artifact@v4
        run: |
          git fetch origin main:main
          echo git diff --name-only --diff-filter=d main~ main | grep .go >> ./changed_files.txt
        with:
          path: './changed_files.txt'