name: Collect Changed Go Files
on:
  push:
    branches: [ main ]

jobs:
  collect-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed .go files
        id: changed-files
        run: |
          # Get the list of changed .go files in the last commit
          changed_files=$(git diff --name-only HEAD^ HEAD -- '*.go' | tr '\n' ' ')
          
          # Create a directory for the changed files
          mkdir -p changed_go_files
          
          # Copy each changed file to the directory
          for file in $changed_files; do
            if [ -f "$file" ]; then
              cp --parents "$file" changed_go_files/
            fi
          done
          
          # Output the list of files for potential use in other steps
          echo "CHANGED_GO_FILES=${changed_files}" >> $GITHUB_OUTPUT

      - name: Upload changed .go files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-go-files
          path: changed_go_files