name: Collect Changed Go Files
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed .go files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD -- '*.go' | tr '\n' ' ')
  
          matrix_json="{\"include\":["
          first=true
          for file in $changed_files; do
          if [ -f "$file" ]; then
          if [ "$first" = false ]; then
          matrix_json+=","
          fi
          
          filename=$(echo "$file" | sed 's/\.go$//')
          matrix_json+="{\"file\":\"$filename\"}"
          first=false
          fi
          done
          matrix_json+="]}"
          
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT
          echo "Generated matrix: $matrix_json"

  deploy:
    name: Deploy ${{ matrix.file }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}
    steps:
      - name: Print file to deploy
        run: echo "Deploying ${{ matrix.file }}"

      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v1.0.1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: ${{ matrix.file }}
          runtime: 'golang121'
          memory: '128Mb'
          execution-timeout: '10s'
          entrypoint: 'com.nedonil.urlshort.UrlShortnerServlet'
          environment: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}